---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alaitp-job-desc
data:
  application.yaml: |-
    server:
      port: 8815

    spring:
      application:
        name: job-description-api
      redis:
        database: 3

    logging:
      file: "${spring.application.name}.log"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-desc
  labels:
    app: job-desc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-desc
  template:
    metadata:
      labels:
        app: job-desc
    spec:
      containers:
        - name: job-desc
          image: localhost:5555/job-desc
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8815
---
apiVersion: v1
kind: Service
metadata:
  name: job-desc
  labels:
    app: job-desc
spec:
  type: ClusterIP
  ports:
    - port: 8815
  selector:
    app: job-desc