---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alaitp-job-desc
data:
  application.yaml: |-
    server:
      port: 8815

    spring:
      application:
        name: job-description-api
      redis:
        database: 3

    logging:
      file: "${spring.application.name}.log"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-desc
  labels:
    app: job-desc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-desc
  template:
    metadata:
      labels:
        app: job-desc
    spec:
      containers:
        - name: job-desc
          image: localhost:5555/job-desc
          imagePullPolicy: Always
          ports:
            - containerPort: 8815
---
apiVersion: v1
kind: Service
metadata:
  name: job-desc
  labels:
    app: job-desc
spec:
  type: ClusterIP
  ports:
    - port: 8815
  selector:
    app: job-desc

---
apiVersion: v1
kind: Service
metadata:
  name: job-desc-node-port
  labels:
    app: job-desc
spec:
  type: NodePort
  selector:
    app: job-desc
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30815