---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alaitp-job-desc
data:
  application.yaml: |-
    server:
      port: 8815

    spring:
      application:
        name: job-description-api
      redis:
        database: 3

    logging:
      file: "${spring.application.name}.log"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-desc
  labels:
    app: job-desc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-desc
  template:
    metadata:
      labels:
        app: job-desc
    spec:
      containers:
        - image: localhost:5555/job-desc
          name: job-desc
          imagePullPolicy: Always
          ports:
            - containerPort: 8815
          readinessProbe: # check the pod is ready for service or not
            httpGet:
              port: 8815
              path: /actuator/health/readiness
            initialDelaySeconds: 60
            timeoutSeconds: 3
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 1
          livenessProbe: # check the pod is alive or not, if it's dead, the pod will restart
            httpGet:
              port: 8815
              path: /actuator/health/liveness
            initialDelaySeconds: 60
            timeoutSeconds: 3
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: job-desc
  labels:
    app: job-desc
spec:
  type: ClusterIP
  ports:
    - port: 8815
  selector:
    app: job-desc

---
apiVersion: v1
kind: Service
metadata:
  name: job-desc-node-port
  labels:
    app: job-desc
spec:
  type: NodePort
  selector:
    app: job-desc
  ports:
    - protocol: TCP
      port: 8815
      targetPort: 8815
      nodePort: 30815